### ISSUE TITLE
http_access management

### ISSUE THREAD

**Issue by meons** [robertdebock/ansible-role-squid#4]
## Proposed feature

Add http_access management.

## Rationale

Without that ACLs are pretty useless.

## Additional context

Define some ACLs and then use them with http_access allow/deny rules.

**Comment by robertdebock** [comment]
That's a cool addition. I've taken the liberty to merge your work in here and add a few things.

Great suggestion, thanks @meons for your creative way of thinking!

It's not fully done, I'll keep the issue open until done.

**Comment by robertdebock** [comment]
Version 2.4.0 has these changes, once again, thanks @meons !
